### ISSUE TITLE
Support for QFN models in `FootprinterModel.ts`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/3d-viewer#36] opened 2024-11-14 20:01 UTC
Model isn't loading for QFN footprinter strings

![Image](https://github.com/user-attachments/assets/959fc930-7be6-4346-a867-1b554b698d23)

/bounty $20

CC @anas-sarkez

**Comment by mrudulpatil18** [comment] 2024-11-15 07:23
on investigation, i feel like the issue is in  [jscad-electronics/lib/Footprinter3d.tsx](https://github.com/tscircuit/jscad-electronics/blob/55f7acf375b1c01a7bb475a99b57f8101c84d8c9/lib/Footprinter3d.tsx#L14) 
 the parser isn't handling QFN - there's no case for "qfn" in the switch statement.

**Comment by anas-sarkez** [comment] 2024-11-15 13:05
@seveibar  Fixed in JsCad electronic repo
check  pr https://github.com/tscircuit/jscad-electronics/pull/78

**Closed** 2024-11-15 18:35 UTC
Labels: 💎 Bounty, 💰 Rewarded
